-- Game
NDefines.NGame.GAME_SPEED_SECONDS = { 6000.0, 0.29, 0.21, 0.10, 0.06 }
NDefines.NGame.COMBAT_LOG_MAX_MONTHS = 6

-- Diplomacy
NDefines.NDiplomacy.BASE_SEND_ATTACHE_COST = 0
NDefines.NDiplomacy.BASE_SEND_ATTACHE_CP_COST = 0

-- Country
NDefines.NCountry.BASE_RESEARCH_SLOTS = 3
NDefines.NCountry.REINFORCEMENT_EQUIPMENT_DELIVERY_SPEED = 1
NDefines.NCountry.REINFORCEMENT_MANPOWER_DELIVERY_SPEED = 30.0
NDefines.NCountry.BASE_STABILITY_WAR_FACTOR = 0
NDefines.NCountry.BASE_STABILITY_PARTY_POPULARITY_FACTOR = 0.2
NDefines.NCountry.WAR_SUPPORT_OFFNSIVE_WAR = -0.1
NDefines.NCountry.WAR_SUPPORT_DEFENSIVE_WAR = 0.1
NDefines.NCountry.BASE_MOBILIZATION_SPEED = 1
NDefines.NCountry.STARTING_COMMAND_POWER = 50.0
NDefines.NCountry.BASE_MAX_COMMAND_POWER = 300.0
NDefines.NCountry.ATTACHE_XP_SHARE = 0
NDefines.NCountry.SPECIAL_FORCES_CAP_BASE = 0
NDefines.NCountry.SPECIAL_FORCES_CAP_MIN = 9999
NDefines.NCountry.STARTING_FUEL_RATIO = 1
NDefines.NCountry.BASE_FUEL_GAIN_PER_OIL = 3.4

-- Resistance
NDefines.NResistance.INITIAL_STATE_RESISTANCE = 0.0
NDefines.NResistance.INITIAL_STATE_COMPLIANCE = 100.0
NDefines.NResistance.RESISTANCE_TARGET_BASE = 0.0
NDefines.NResistance.RESISTANCE_TARGET_MODIFIER_HAS_CLAIM = 0.0
NDefines.NResistance.RESISTANCE_TARGET_MODIFIER_PER_STABILITY_LOSS = 0
NDefines.NResistance.RESISTANCE_TARGET_MODIFIER_PER_COMPLIANCE = 0
NDefines.NResistance.RESISTANCE_TARGET_MODIFIER_IS_AT_PEACE = 0
NDefines.NResistance.RESISTANCE_TARGET_MODIFIER_STATE_VP = {
	0,   0,
	0,   0,
	0,   0,
	0,   0,
}
NDefines.NResistance.RESISTANCE_TARGET_MODIFIER_OCCUPIED_CAPITULATED = 0.0
NDefines.NResistance.RESISTANCE_TARGET_MODIFIER_OCCUPIED_IS_EXILE_MIN = 0.0
NDefines.NResistance.RESISTANCE_TARGET_MODIFIER_OCCUPIED_IS_EXILE_MAX = 0.0
NDefines.NResistance.RESISTANCE_TARGET_MODIFIER_POP_LOW = 0.0
NDefines.NResistance.RESISTANCE_TARGET_MODIFIER_POP_VERY_LOW = 0.0
NDefines.NResistance.RESISTANCE_DECAY_BASE = 10.0
NDefines.NResistance.RESISTANCE_DECAY_MIN = 9.0
NDefines.NResistance.MIN_DAMAGE_TO_GARRISONS_MODIFIER = 0.0
NDefines.NResistance.RESISTANCE_GROWTH_BASE = -1.0
NDefines.NResistance.RESISTANCE_GROWTH_MIN = -1.0
NDefines.NResistance.RESISTANCE_GROWTH_MAX = -1.0
NDefines.NResistance.COMPLIANCE_GROWTH_BASE = 100.0
NDefines.NResistance.COMPLIANCE_GROWTH_MIN = 100.0
NDefines.NResistance.COMPLIANCE_DECAY_AT_MAX_COMPLIANCE = 0
NDefines.NResistance.COMPLIANCE_DECAY_PER_EXILE_LEGITIMACY = 0
NDefines.NResistance.RESISTANCE_ACTIVITY_CHANCE_AT_MAX_RESISTANCE = 0
NDefines.NResistance.RESISTANCE_ACTIVITY_MIN_GARRISON_PENETRATE_CHANCE = 0
NDefines.NResistance.RESISTANCE_TARGET_TO_REENABLE_RESISTANCE = 100
NDefines.NResistance.GARRISON_LOG_MAX_MONTHS = 0
NDefines.NResistance.GARRISON_MANPOWER_MIN_DELIVERY_SPEED = 1
NDefines.NResistance.GARRISON_EQUIPMENT_DELIVERY_SPEED = 2000.0
NDefines.NResistance.GARRISON_MANPOWER_LOST_BY_ATTACK = 0.0
NDefines.NResistance.GARRISON_EQUIPMENT_LOST_BY_ATTACK = 0.0
NDefines.NResistance.MAXIMUM_GARRISON_HARDNESS_WHEN_ATTACKED = 1.0
NDefines.NResistance.INITIAL_HISTORY_COMPLIANCE = 100.0
NDefines.NResistance.INITIAL_GARRISON_STRENGTH = 100

NDefines.NProduction.BASE_FACTORY_SPEED = 4.5
NDefines.NProduction.BASE_FACTORY_SPEED_MIL = 5
NDefines.NProduction.LEND_LEASE_DELIVERY_TOTAL_DAYS = 14
NDefines.NProduction.ANNEX_FUEL_RATIO = 1.0
NDefines.NProduction.MIN_POSSIBLE_TRAINING_MANPOWER = 20000000
NDefines.NProduction.MIN_FIELD_TO_TRAINING_MANPOWER_RATIO = 0.9
NDefines.NProduction.EQUIPMENT_MODULE_ADD_XP_COST = 0
NDefines.NProduction.EQUIPMENT_MODULE_REPLACE_XP_COST = 0
NDefines.NProduction.EQUIPMENT_MODULE_CONVERT_XP_COST = 0
NDefines.NProduction.EQUIPMENT_MODULE_REMOVE_XP_COST = 0

NDefines.NTechnology.BASE_RESEARCH_POINTS_SAVED = 60.0
NDefines.NTechnology.BASE_YEAR_AHEAD_PENALTY_FACTOR = 4

NDefines.NPolitics.ARMY_LEADER_COST = 1
NDefines.NPolitics.NAVY_LEADER_COST = 1

NDefines.NDeployment.BASE_DEPLOYMENT_TRAINING = 6

-- Military
NDefines.NMilitary.PIERCING_THRESHOLDS = {
	1.00,
	0.75,
	0.99,
	0.98,
	0.96,
	0.94,
	0.92,
	0.90,
	0.88,
	0.86,
	0.84,
	0.82,
	0.80,
	0.78,
	0.76,
	0.74,
	0.72,
	0.70,
	0.68,
	0.66,
	0.64,
	0.62,
	0.60,
	0.58,
	0.56,
	0.54,
	0.52,
	0.50,
	0.48,
	0.46,
	0.44,
	0.42,
	0.40,
	0.38,
	0.36,
	0.34,
	0.32,
	0.30,
	0.28,
	0.26,
	0.24,
	0.22,
	0.20,
	0.18,
	0.16,
	0.14,
	0.12,
	0.10,
	0.08,
	0.06,
	0.04,
	0.02,
	0.00, --there isn't much point setting this higher than 0
}
NDefines.NMilitary.PIERCING_THRESHOLD_DAMAGE_VALUES = {
	1.00,	--with 100% piercing
	0.950,	--with 99% piercing; so there's an extra advantage in going for higher armor
	0.940,
	0.930,
	0.920,
	0.910,
	0.900,
	0.890,
	0.880,
	0.870,
	0.860,
	0.850,
	0.840,
	0.830,
	0.820,
	0.810,
	0.800,
	0.790,
	0.780,
	0.770,
	0.760,
	0.750,
	0.740,
	0.730,
	0.720,
	0.710,
	0.700,
	0.690,
	0.680,
	0.670,
	0.660,
	0.650,
	0.640,
	0.630,
	0.620,
	0.610,
	0.600,
	0.590,
	0.580,
	0.570,
	0.560,
	0.550,
	0.540,
	0.530,
	0.520,
	0.510,
	0.500,
	0.490,
	0.480,
	0.470,
	0.460,
	0.450, --with 0% piercing
}
NDefines.NMilitary.ZERO_ORG_MOVEMENT_MODIFIER = -0.2
NDefines.NMilitary.INFRA_ORG_IMPACT = 0.15
NDefines.NMilitary.CORPS_COMMANDER_DIVISIONS_CAP = 0
NDefines.NMilitary.FIELD_MARSHAL_DIVISIONS_CAP = 0
NDefines.NMilitary.FIELD_MARSHAL_ARMIES_CAP = 0
NDefines.NMilitary.MIN_DIVISION_BRIGADE_HEIGHT = 5
NDefines.NMilitary.MAX_DIVISION_SUPPORT_WIDTH = 2
NDefines.NMilitary.BASE_DIVISION_BRIGADE_GROUP_COST = 0
NDefines.NMilitary.BASE_DIVISION_BRIGADE_CHANGE_COST = 0
NDefines.NMilitary.BASE_DIVISION_SUPPORT_SLOT_COST = 0
NDefines.NMilitary.MAX_ARMY_EXPERIENCE = 999
NDefines.NMilitary.MAX_NAVY_EXPERIENCE = 999
NDefines.NMilitary.MAX_AIR_EXPERIENCE = 999
NDefines.NMilitary.LAND_COMBAT_STR_DAMAGE_MODIFIER = 0.005
NDefines.NMilitary.LAND_COMBAT_ORG_DAMAGE_MODIFIER = 0.015
NDefines.NMilitary.LAND_COMBAT_ORG_ARMOR_ON_SOFT_DICE_SIZE = 5
NDefines.NMilitary.LAND_COMBAT_STR_ARMOR_DEFLECTION_FACTOR = 1.0
NDefines.NMilitary.RELIABILTY_RECOVERY = 0.05
NDefines.NMilitary.BASE_CHANCE_TO_AVOID_HIT = 80
NDefines.NMilitary.CHANCE_TO_AVOID_HIT_AT_NO_DEF = 75
NDefines.NMilitary.PREFERRED_TACTIC_CHARACTER_SKILL_LEVEL_REQUIRED = 1
NDefines.NMilitary.RIVER_CROSSING_PENALTY = -0.2
NDefines.NMilitary.RIVER_CROSSING_PENALTY_LARGE = -0.4
NDefines.NMilitary.ARMY_LEADER_XP_GAIN_PER_UNIT_IN_COMBAT = 0.0
NDefines.NMilitary.CONSTANT_XP_RATIO_FOR_MULTIPLE_LEADERS_IN_SAME_COMBAT = 0
NDefines.NMilitary.BASE_LEADER_TRAIT_GAIN_XP = 0.0
NDefines.NMilitary.DEPLOY_TRAINING_MAX_LEVEL = 2
NDefines.NMilitary.EXPERIENCE_COMBAT_FACTOR = 0.05
NDefines.NMilitary.EQUIPMENT_COMBAT_LOSS_FACTOR = 1
NDefines.NMilitary.SUPPLY_GRACE = 168 --?????
NDefines.NMilitary.ENCIRCLED_DISBAND_MANPOWER_FACTOR = 0.5
NDefines.NMilitary.ORG_LOSS_FACTOR_ON_CONQUER = 0.05
NDefines.NMilitary.COMBAT_SUPPLY_LACK_ATTACKER_ATTACK = -0.20
NDefines.NMilitary.LAND_EQUIPMENT_BASE_COST = 1
NDefines.NMilitary.LAND_EQUIPMENT_RAMP_COST = 0
NDefines.NMilitary.NAVAL_EQUIPMENT_BASE_COST = 0
NDefines.NMilitary.NAVAL_EQUIPMENT_RAMP_COST = 0
NDefines.NMilitary.AIR_EQUIPMENT_BASE_COST = 0
NDefines.NMilitary.AIR_EQUIPMENT_RAMP_COST = 0
NDefines.NMilitary.PROMOTE_LEADER_CP_COST = 0.0
NDefines.NMilitary.FIELD_MARSHAL_ARMY_BONUS_RATIO = 1
NDefines.NMilitary.UNIT_LEADER_USE_NONLINEAR_XP_GAIN = false
NDefines.NMilitary.NEW_COMMANDER_RANDOM_PERSONALITY_TRAIT_CHANCES = {
	0.0,
	0.0
}
NDefines.NMilitary.XP_GAIN_FACTOR_FOR_MAX_RELATIVE_COMBAT_DAMAGE = 1.0
NDefines.NMilitary.XP_GAIN_PER_OVERRUN_UNIT = 0.0
NDefines.NMilitary.XP_GAIN_FOR_SHATTERING = 0.0

-- Air/Military -- CAS Defines --
NDefines.NMilitary.AIR_SUPPORT_BASE = 0.16
NDefines.NMilitary.LAND_AIR_COMBAT_STR_DAMAGE_MODIFIER = 0.06
NDefines.NMilitary.LAND_AIR_COMBAT_ORG_DAMAGE_MODIFIER = 0.06
NDefines.NMilitary.ANTI_AIR_TARGETTING_TO_CHANCE = 0.001

-- Air
NDefines.NAir.AIR_WING_FLIGHT_SPEED_MULT = 3
NDefines.NAir.COMBAT_DAMAGE_SCALE = 1
NDefines.NAir.COMBAT_DAMAGE_SCALE_CARRIER = 4
NDefines.NAir.ACCIDENT_CHANCE_RELIABILITY_MULT = 5.0
NDefines.NAir.AIR_DEPLOYMENT_DAYS = 0
NDefines.NAir.SECONDARY_DAMAGE_STRAT = 0.1
NDefines.NAir.MISSION_COMMAND_POWER_COSTS = {
	0.0, -- AIR_SUPERIORITY
	0.0, -- CAS
	0.0, -- INTERCEPTION
	0.0, -- STRATEGIC_BOMBER
	0.0, -- NAVAL_BOMBER
	0.0, -- DROP_NUKE
	0.0, -- PARADROP
	0.0, -- NAVAL_KAMIKAZE
    0.0, -- PORT_STRIKE
	0.0, -- ATTACK_LOGISTICS
	0.0, -- AIR_SUPPLY
	0.0, -- TRAINING
	0.0, -- NAVAL_MINES_PLANTING
	0.0, -- NAVAL_MINES_SWEEPING
	0.0, -- RECON
	0.0, -- NAVAL_PATROL
}
NDefines.NAir.MISSION_FUEL_COSTS = {  -- fuel cost per plane for each mission
	1.0, -- AIR_SUPERIORITY
	1.0, -- CAS
	1.0, -- INTERCEPTION
	1.0, -- STRATEGIC_BOMBER
	1.0, -- NAVAL_BOMBER
	1.0, -- DROP_NUKE
	1.0, -- PARADROP
	1.0, -- NAVAL_KAMIKAZE
	1.0, -- PORT_STRIKE
	1.0, -- ATTACK_LOGISTICS
	1.0, -- AIR_SUPPLY
	0.5, -- TRAINING
	1.0, -- NAVAL_MINES_PLANTING
	1.0, -- NAVAL_MINES_SWEEPING
	1.0, -- RECON
	1.0, -- NAVAL_PATROL
}
NDefines.NAir.AIR_WING_XP_LOSS_REDUCTION_OVER_FRIENDLY_TERRITORY_FACTOR = 0     
NDefines.NAir.AIR_WING_XP_AIR_VS_AIR_COMBAT_GAIN = 0                            
NDefines.NAir.AIR_WING_XP_GROUND_MISSION_COMPLETED_GAIN = 0                 
NDefines.NAir.AIR_WING_XP_RECON_MISSION_COMPLETED_GAIN = 0                  
NDefines.NAir.AIR_WING_XP_LOSS_WHEN_KILLED = 0       
NDefines.NAir.AIR_WING_XP_TRAINING_MAX = 2.0                         
NDefines.NAir.AIR_WING_XP_MAX = 0                                             
NDefines.NAir.AIR_WING_XP_LEVELS = { 0 }
NDefines.NAir.BOMBING_TARGETING_RANDOM_FACTOR = 0.05
NDefines.NAir.MAX_QUICK_WING_SELECTION = 5
NDefines.NAir.AIR_WING_XP_TRAINING_MISSION_GAIN_DAILY = 0.2
NDefines.NAir.AIR_WING_COUNTRY_XP_FROM_TRAINING_FACTOR = 0.4
NDefines.NAir.ACE_DEATH_CHANCE_BASE = 0				
NDefines.NAir.ACE_DEATH_BY_OTHER_ACE_CHANCE = 0				
NDefines.NAir.ACE_DEATH_CHANCE_PLANES_MULT = 0		
NDefines.NAir.ACE_EARN_CHANCE_BASE = 0				
NDefines.NAir.ACE_EARN_CHANCE_PLANES_MULT = 0	
NDefines.NAir.SUPPLY_NEED_FACTOR = 0.28				
NDefines.NAir.ANTI_AIR_PLANE_DAMAGE_FACTOR = 0.01 
NDefines.NAir.ANTI_AIR_PLANE_DAMAGE_CHANCE = 0.01
NDefines.NAir.ANTI_AIR_ATTACK_TO_DAMAGE_REDUCTION_FACTOR = 1
NDefines.NAir.ANTI_AIR_MAXIMUM_DAMAGE_REDUCTION_FACTOR = 1.2
NDefines.NAir.AIR_MORE_GROUND_CREWS_COST = 400.0
NDefines.NAir.AIR_COMBAT_FINAL_DAMAGE_SCALE = 0.2
NDefines.NAir.COMBAT_MULTIPLANE_CAP = 2.0
NDefines.NAir.ACCIDENT_CHANCE_BASE = 0.0

--Focus
NDefines.NFocus.MAX_SAVED_FOCUS_PROGRESS = 20

--Supply
NDefines.NSupply.CAPITAL_SUPPLY_BASE = 8.0
NDefines.NSupply.CAPITAL_SUPPLY_CIVILIAN_FACTORIES = 0.9
NDefines.NSupply.CAPITAL_SUPPLY_MILITARY_FACTORIES = 0.9
NDefines.NSupply.CAPITAL_SUPPLY_DOCKYARDS = 0.9
NDefines.NSupply.CAPITAL_INITIAL_SUPPLY_FLOW = 10.0
NDefines.NSupply.CAPITAL_STARTING_PENALTY_PER_PROVINCE = 0.25
NDefines.NSupply.CAPITAL_ADDED_PENALTY_PER_PROVINCE = 0.6
NDefines.NSupply.NODE_INITIAL_SUPPLY_FLOW = 4.2
NDefines.NSupply.NAVAL_BASE_INITIAL_SUPPLY_FLOW = 7.0
NDefines.NSupply.NAVAL_BASE_STARTING_PENALTY_PER_PROVINCE = 0.5
NDefines.NSupply.NAVAL_BASE_ADDED_PENALTY_PER_PROVINCE = 0.5
NDefines.NSupply.NODE_FLOW_BONUS_PER_RAIL_LEVEL = 0.7
NDefines.NSupply.FLOATING_HARBOR_INITIAL_SUPPLY_FLOW = 4
NDefines.NSupply.FLOATING_HARBOR_STARTING_PENALTY_PER_PROVINCE = 0.4
NDefines.NSupply.FLOATING_HARBOR_ADDED_PENALTY_PER_PROVINCE = 0.6
NDefines.NSupply.FLOATING_HARBOR_BASE_SUPPLY = 20.0
NDefines.NSupply.FLOATING_HARBOR_BASE_DURATION = 28
NDefines.NSupply.FLOATING_HARBOR_DURATION_RATIO_AT_MIN_HP = 0.1
NDefines.NSupply.SUPPLY_FLOW_DROP_REDUCTION_AT_MAX_INFRA = 0.60
NDefines.NSupply.SUPPLY_FLOW_PENALTY_CROSSING_RIVERS = 0.05
NDefines.NSupply.SUPPLY_FLOW_PENALTY_CROSSING_RIVERS = 0.05
NDefines.NSupply.SUPPLY_HUB_FULL_MOTORIZATION_BONUS = 3
NDefines.NSupply.SUPPLY_HUB_FULL_MOTORIZATION_TRUCK_COST = 50.0
NDefines.NSupply.SUPPLY_HUB_FULL_MOTORIZATION_TRUCK_COST = 50.0
NDefines.NSupply.SUPPLY_HUB_MOTORIZATION_MARGINAL_EFFECT_DECAY = 1.0
NDefines.NSupply.RAILWAY_FLOW_PER_LEVEL = 7.0
NDefines.NSupply.NAVAL_FLOW_PER_LEVEL = 5.0
NDefines.NSupply.INFRA_TO_SUPPLY = 0.6
NDefines.NSupply.VP_TO_SUPPLY_BASE = 0.4
NDefines.NSupply.SUPPLY_FROM_DAMAGED_INFRA = 0.2
NDefines.NSupply.SUPPLY_BASE_MULT = 0.4
NDefines.NSupply.RAILWAY_CONVERSION_COOLDOWN = 0
NDefines.NSupply.RAILWAY_CONVERSION_COOLDOWN_CORE = 0
NDefines.NSupply.MIN_TRAIN_SUPPLY_FACTOR = 0.2
NDefines.NSupply.DAYS_TO_START_GIVING_SUPPLY_AFTER_MOVING_SUPPLY_CAPITAL = 4
NDefines.NSupply.ALERT_LOW_SUPPLY_LEVEL = 0.9
NDefines.NSupply.ALERT_VERY_LOW_SUPPLY_LEVEL = 0.5

--MIO
NDefines.NIndustrialOrganisation.ASSIGN_DESIGN_TEAM_PP_COST_PER_DAY = 0
NDefines.NIndustrialOrganisation.DESIGN_TEAM_CHANGE_XP_COST = 1

--Special Projects
NDefines.NProject.DEFAULT_STOP_PROJECT_DAYS = 0
NDefines.NProject.DAYS_TO_REMOVE_SCIENTIST = 0
NDefines.NProject.DEFAULT_PROJECT_COMPLETION_SCIENTIST_EXPERIENCE_GAIN = 0
NDefines.NProject.RECRUIT_SCIENTIST_ONE_TRAIT_CHANCE = 0
NDefines.NProject.SCIENTIST_BASIC_RESEARCH_DAILY_XP_GAIN = 0
NDefines.NProject.RECRUIT_SCIENTIST_COST = {0,0,0,0}
NDefines.NProject.SCIENTIST_SKILL_LEVEL_THRESHOLDS = {0,0,0,0,0}